version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi-social-loader
    ports:
      - "8443:8443"
      - "8081:8081"
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
